const missions = [
    { question: "Qual é o dispositivo que mais consome energia?", answer: "ar condicionado" },
    { question: "Qual dispositivo consome mais energia em standby?", answer: "tv" },
    { question: "Qual dispositivo deve ser desligado após o uso para economizar energia?", answer: "máquina de lavar" },
    { question: "Qual dispositivo é mais eficiente em termos de consumo de energia?", answer: "led" },
    { question: "Qual é o dispositivo que deve ser desligado após o uso para evitar desperdício?", answer: "micro-ondas" },
    { question: "Qual dispositivo deve ser mantido em modo de suspensão para economizar energia?", answer: "computador" },
    { question: "Qual é o dispositivo que usa energia para resfriar o ambiente?", answer: "ar condicionado" },
    { question: "Qual é o dispositivo que deve ser usado em vez do ar condicionado para economizar energia?", answer: "ventilador" },
    { question: "Qual dispositivo deve ser desligado após preparar a comida?", answer: "cafeteira elétrica" },
    { question: "Qual dispositivo é mais eficiente para cozinhar alimentos com pouco consumo de energia?", answer: "forno elétrico" },
    { question: "Qual é o dispositivo usado para secar roupas?", answer: "secadora de roupas" },
    { question: "Qual dispositivo deve ser desligado após a limpeza do ambiente?", answer: "aspirador de pó" },
    { question: "Qual é o dispositivo que pode economizar energia ao usar a potência mínima?", answer: "liquidificador" },
    { question: "Qual é o dispositivo que deve ser limpo regularmente para manter a eficiência?", answer: "purificador de ar" },
    { question: "Qual dispositivo deve ser usado em horários programados para economizar energia?", answer: "aspirador robô" },
    { question: "Qual dispositivo pode usar potência baixa para economizar energia ao secar o cabelo?", answer: "secador de cabelo" },
    { question: "Qual dispositivo deve ser desligado quando a bateria está carregada?", answer: "barbeador elétrico" },
    { question: "Qual é o dispositivo que deve ser usado para economizar energia ao cozinhar?", answer: "fogão a indução" },
    { question: "Qual dispositivo pode ter potência ajustável para economizar energia ao aquecer alimentos?", answer: "micro-ondas" },
    { question: "Qual dispositivo deve ser desligado após o uso para evitar desperdício de energia?", answer: "impressora" },
    { question: "Qual é o dispositivo que deve ser usado para resfriar o ar em ambientes internos?", answer: "climatizador de ar" },
    { question: "Qual é o dispositivo que deve ser usado para resfriar o ambiente?", answer: "ventilador de teto" },
    { question: "Qual dispositivo deve ser usado para preparar alimentos rapidamente?", answer: "torradeira" },
    { question: "Qual é o dispositivo que deve ser usado para manter alimentos frescos?", answer: "geladeira" },
    { question: "Qual é o dispositivo que pode economizar energia ao aquecer água rapidamente?", answer: "aquecedor elétrico" },
    { question: "Qual dispositivo deve ser usado para aumentar a eficiência da iluminação?", answer: "lâmpada LED" },
    { question: "Qual dispositivo deve ser usado para melhorar a qualidade do ar em ambientes fechados?", answer: "umidificador" },
    { question: "Qual é o dispositivo usado para manter a temperatura da água?", answer: "aquecedor elétrico" },
    { question: "Qual dispositivo deve ser usado para filtrar o ar de forma eficiente?", answer: "purificador de ar" },
    { question: "Qual é o dispositivo que deve ser usado para manter a temperatura ideal da comida?", answer: "micro-ondas" },
    { question: "Qual dispositivo pode ser usado para armazenar alimentos por longos períodos?", answer: "freezer" },
    { question: "Qual é o dispositivo usado para fazer a limpeza a seco de roupas?", answer: "lavadora a seco" },
    { question: "Qual dispositivo é utilizado para desumidificar o ar?", answer: "desumidificador" },
    { question: "Qual é o dispositivo usado para aspirar sujeira e poeira do chão?", answer: "aspirador de pó" },
    { question: "Qual dispositivo deve ser usado para automatizar a irrigação do jardim?", answer: "sistema de irrigação automatizado" },
    { question: "Qual é o dispositivo que deve ser usado para cozinhar alimentos de forma rápida e eficiente?", answer: "panela de pressão elétrica" }
];
